
services:
  protoc-py-better:
    image: ghcr.io/akasandra/protoc-py-better:3.12
    build:
      context: .
      dockerfile: py-better.Dockerfile
    restart: no
    entrypoint:
      - /bin/sh
      - -c
      - |
        # 1. Setup Output Directory
        mkdir -p "/source/$${PROTOC_PATH_PY}"
        echo "Cleaning old generated Python files..."
        find "/source/$${PROTOC_PATH_PY}" -name '*.py' -delete

        # 2. Absolute path to the verified binary
        PLUGIN_BIN="/usr/local/bin/protoc-gen-python_betterproto"

        # 3. Compile
        protoc \
          --plugin=protoc-gen-python_betterproto="$$PLUGIN_BIN" \
          --proto_path="/source/$${PROTO_SOURCES_DIR}" \
          --python_betterproto_out="/source/$${PROTOC_PATH_PY}" \
          --python_betterproto_opt=pydantic_dataclasses \
          `find "/source/$${PROTO_SOURCES_DIR}" -maxdepth 1 -name "*.proto"`